# Generated by Django 5.0 on 2025-11-03 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=15)),
                ('party_size', models.IntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('seated', 'Seated'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('estimated_wait_time', models.IntegerField(help_text='Wait time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'waitlist',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=10, unique=True)),
                ('capacity', models.IntegerField(default=4)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('cleaning', 'Cleaning')], default='available', max_length=20)),
                ('location', models.CharField(blank=True, help_text='e.g., Indoor, Outdoor, VIP', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('occupied_since', models.DateTimeField(blank=True, null=True)),
                ('assigned_server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tables',
                'ordering': ['table_number'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('party_size', models.IntegerField()),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('seated', 'Seated'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='tables.table')),
            ],
            options={
                'db_table': 'reservations',
                'ordering': ['-reservation_date', '-reservation_time'],
            },
        ),
        migrations.CreateModel(
            name='TableCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tables', models.ManyToManyField(related_name='combinations', to='tables.table')),
            ],
            options={
                'db_table': 'table_combinations',
            },
        ),
    ]
